# This config file is adapted from the one in the GitHub Pages tutorial. 

theme: minima
title: REET Workshop: Requirements Engineering Education and Training
# author: Zach Oster
email: reet20 at easychair dot org
description: > # this means to ignore newlines until "baseurl:"
  Requirements Engineering Education and Training workshop series. 
  REET'20 will be held in conjunction with RE'20 in Zurich, Switzerland, on August 31, 2020.
  
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  zach-oster # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to true to include excerpts on the homepage
